export const LOAD_POKEMONS_START = "LOAD_POKEMONS_START";
export const LOAD_POKEMONS_SUCCUESS = "LOAD_POKEMONS_SUCCUESS";
export const LOAD_POKEMONS_ERROR = "LOAD_POKEMONS_ERROR";

export const LOAD_CAUGHT_POKEMONS_START = "LOAD_CAUGHT_POKEMONS_START";
export const LOAD_CAUGHT_POKEMONS_SUCCUESS = "LOAD_CAUGHT_POKEMONS_SUCCUESS";
export const LOAD_CAUGHT_POKEMONS_ERROR = "LOAD_CAUGHT_POKEMONS_ERROR";

export const LOAD_POKEMON_INFO_START = "LOAD_POKEMON_INFO_START";
export const LOAD_POKEMON_INFO_SUCCUESS = "LOAD_POKEMON_INFO_SUCCUESS";
export const LOAD_POKEMON_INFO_ERROR = "LOAD_POKEMON_INFO_ERROR";

export const CATCH_POKEMON_START = "CATCH_POKEMON_START";
export const CATCH_POKEMON_SUCCUESS = "CATCH_POKEMON_SUCCUESS";
export const CATCH_POKEMON_ERROR = "CATCH_POKEMON_ERROR";

export const LOCATION_CHANGE = "LOCATION_CHANGE";